"""Generate the canonical tool reference in README.md from the registered MCP tools.

The curated, grouped tool tables in README stay hand-written (they read well); this
script fills a single AUTOGEN block with the complete, signature-accurate list so
there is one source of truth that can never silently drift. A test
(test_followups.test_readme_autogen_block_current) fails if the block is stale.

Usage (from the repo root):
    python -m tools.gen_readme_tools          # rewrite README between the markers
    python -m tools.gen_readme_tools --check  # exit 1 if README is out of date
"""
from __future__ import annotations

import asyncio
import inspect
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from inav_mcp import server

START  = "<!-- TOOLS:AUTOGEN:START -->"
END    = "<!-- TOOLS:AUTOGEN:END -->"
README = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "README.md"))


def _signature(fn) -> str:
    """Render a callable's signature as `(a, b=default, …)` (skip *args/**kwargs noise)."""
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return "(...)"
    parts = []
    for name, prm in sig.parameters.items():
        if prm.default is inspect.Parameter.empty:
            parts.append(name)
        else:
            parts.append(f"{name}={prm.default!r}")
    return "(" + ", ".join(parts) + ")"


def _first_doc_line(fn) -> str:
    for line in (fn.__doc__ or "").strip().split("\n"):
        if line.strip():
            return line.strip()
    return ""


def generate_block() -> str:
    """Build the full AUTOGEN markdown block (markers included) from registered tools."""
    tools = asyncio.run(server.mcp.list_tools())
    rows = []
    for t in sorted(tools, key=lambda x: x.name):
        fn   = getattr(server, t.name, None)
        sig  = _signature(fn) if callable(fn) else "(...)"
        desc = _first_doc_line(fn) if callable(fn) else (t.description or "").split("\n")[0].strip()
        rows.append(f"| `{t.name}{sig}` | {desc} |")
    body = "| Tool | Description |\n|---|---|\n" + "\n".join(rows)
    return (
        f"{START}\n"
        f"_{len(tools)} tools — auto-generated by `tools/gen_readme_tools.py`; do not edit by hand._\n\n"
        f"{body}\n"
        f"{END}"
    )


def _rewrite(text: str, block: str) -> str:
    if START in text and END in text:
        return text[: text.index(START)] + block + text[text.index(END) + len(END):]
    # No markers yet — append a fresh section.
    return text.rstrip() + "\n\n## Full tool reference\n\n" + block + "\n"


def main(argv: list[str]) -> int:
    with open(README, encoding="utf-8") as f:
        text = f.read()
    new_text = _rewrite(text, generate_block())

    if "--check" in argv:
        if new_text != text:
            print("README tool reference is OUT OF DATE — run: python -m tools.gen_readme_tools")
            return 1
        print("README tool reference is up to date.")
        return 0

    if new_text != text:
        with open(README, "w", encoding="utf-8") as f:
            f.write(new_text)
        print("README tool reference regenerated.")
    else:
        print("README tool reference already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
